{{- range $svcName, $originalSvc := .Values.apps }}
{{- $svc := mergeOverwrite (deepCopy $.Values.defaults) (deepCopy $.Values.global) (deepCopy $originalSvc) }}
{{- $ctx := (dict "svcName" $svcName "svc" $svc "root" $) }}

{{- if and $svc.serviceAccount.create  $svc.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nv-svc-farm.app.serviceAccountName" $ctx  }}
  labels:
    {{- include "nv-svc-farm.app.labels" $ctx | nindent 4 }}
  {{- with $svc.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
{{- $imagePullSecretsList := list }}
{{- range $svc.imagePullSecrets }}
{{- $imagePullSecretsList = append $imagePullSecretsList (dict "name" . ) }}
{{- ( toYaml $imagePullSecretsList) | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}