# -*- coding: utf-8 -*-

[tox]
isolated_build = True
envlist =
  coverage-erase
  py{312}
  #py{310,312}
  coverage-report

[base]
setenv =
  POETRY_CACHE_DIR = {env:POETRY_CACHE_DIR:}
  COVERAGE_FILE = .tox/.coverage
package_root = nv/svc/farm

[testenv]
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry show
  poetry install -v --sync
  coverage run --source={[base]package_root}/ --parallel-mode -m pytest {posargs:-s -vv tests/}

### Build
[testenv:build]
basepython = python3.12
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry build --format=wheel

# Start application
[testenv:start]
allowlist_externals = poetry
skip_install = true
passenv = 
  NV__SVC__GLOBAL__CONFIG_FILEPATH
  JOBS_API_KEY
  MYSQL_PASSWORD
setenv =
  {[base]setenv}
commands =
  poetry install -v --without dev
  {posargs}

### Coverage
[testenv:coverage-erase]
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry install -v --only dev
  coverage erase

[testenv:coverage-report]
allowlist_externals = poetry
skip_install = true
commands_pre =
    {[testenv]commands}
setenv =
  {[base]setenv}
commands =
  poetry install -v --only=dev
  coverage combine
  coverage html
  coverage lcov
  coverage report -m

### Update/freeze dependencies
[testenv:deps.freeze]
basepython = python3.12
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry update

### Linters
[testenv:linters]
deps =
  {[testenv:bandit]deps}
  {[testenv:flake8]deps}
  {[testenv:pylint]deps}
commands =
  {[testenv:bandit]commands}
  {[testenv:flake8]commands}
  #{[testenv:pylint]commands}

### Linter: Bandit
[testenv:bandit]
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry install -v --only=dev
  # TODO: address bandit issues
  # bandit -c pyproject.toml -r {[base]package_root}/

### Linter: Flake8
[testenv:flake8]
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry install -v --only=dev
  flake8

### Linter: Pylint
[testenv:pylint]
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry install -v
  pylint

### Docs
[testenv:docs]
allowlist_externals = 
  mkdocs
  poetry
  cp
setenv =
  {[base]setenv}
commands =
  poetry install -v
  cp README.md docs/index.md
  mkdocs build -d '{envtmpdir}/html'

### Docs Live Server
[testenv:docs-server]
allowlist_externals = 
  mkdocs
  poetry
  cp
setenv =
  {[base]setenv}
commands =
  poetry install -v
  cp README.md docs/index.md
  mkdocs serve

### Publish
[testenv:publish]
basepython = python3.12
allowlist_externals = poetry
skip_install = true
passenv =
  OMNI_ARTIFACTORY_*
setenv =
  {[base]setenv}
  POETRY_HTTP_BASIC_NVIDIA_CT_OMNIVERSE_LOCAL_USERNAME = {env:OMNI_ARTIFACTORY_USERNAME}
  POETRY_HTTP_BASIC_NVIDIA_CT_OMNIVERSE_LOCAL_PASSWORD = {env:OMNI_ARTIFACTORY_PASSWORD}
commands =
  poetry -v publish --repository nvidia-ct-omniverse-local

### Check
[testenv:check-format]
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry install -v
  isort --check --diff {[base]package_root}/ tests/
  black --check --diff {[base]package_root}/ tests/ --config pyproject.toml

### Format
[testenv:fix-format]
allowlist_externals = poetry
skip_install = true
setenv =
  {[base]setenv}
commands =
  poetry install -v
  isort {[base]package_root}/ tests/
  black {[base]package_root}/ tests/ --config pyproject.toml
