# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""facilities monitoring metrics facilities middleware."""

import asyncio
import math
import time

import fastapi
import prometheus_client as prometheus
from opentelemetry.metrics import Observation
from starlette import routing
from starlette.middleware import base

from .facilities import MetricsFacility
from .utils import get_prometheus_registry, DEFAULT_INSTANCE_NAME

_COUNT_LOCK = asyncio.Lock()
_ACTIVE_COUNTS = {}


_metrics_facility = MetricsFacility("middleware")


def _get_active_count_observables(options):
    observations = []
    # Generate observations based on each count.
    for item in _ACTIVE_COUNTS.items():
        (method, route, instance), count = item
        labels = {"method": method, "route": route, "instance": instance}
        observations.append(Observation(count, labels))
    return observations


_REQUESTS = _metrics_facility.counter(
    name="http_requests_total",
    description="Total amount of requests by method and route",
    unit="requests"
)

_metrics_facility.observable_gauge(
    name="http_requests_active",
    description="Current active requests by method and route",
    callbacks=_get_active_count_observables,
    unit="requests"
)

_RESPONSES = _metrics_facility.counter(
    name="http_requests_responses",
    description="Total amount of responses by method, route, return code and exception_type",
    unit="responses"
)

_REQUEST_PROCESSING_TIME = _metrics_facility.histogram(
    name="http_request_processing_time",
    description="Histogram of request processing time per route in milliseconds",
    unit="milliseconds"
)

_UNMATCHED_ROUTE = _metrics_facility.counter(
    name="http_unmatched_routes",
    description="Total amount of requests that have no route.",
    unit="requests"
)


async def _increment_active_count(method: str, route: str, instance: str, amount: int):
    async with _COUNT_LOCK:
        key = (method, route, instance)
        _ACTIVE_COUNTS[key] = _ACTIVE_COUNTS.get(key, 0) + amount


class MetricsMiddleware(base.BaseHTTPMiddleware):
    """
    Middleware for capturing metrics related to HTTP requests and responses.

    Methods:
    - dispatch: Captures metrics before and after handling the request.

    """

    def __init__(self, *args, **kwargs) -> None:
        """Metrics middleware constructor."""
        super().__init__(*args, **kwargs)
        # NOTE: record 0 to avoid missing metrics per: https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics
        _REQUESTS.add(0)
        _RESPONSES.add(0)
        _REQUEST_PROCESSING_TIME.record(0)
        _UNMATCHED_ROUTE.add(0)

    async def dispatch(self, request, call_next):
        """
        Capture metrics before and after handling the HTTP request.

        Parameters:
        - request (Request): The incoming HTTP request.
        - call_next (callable): The next middleware or route handler to call in the chain.

        Returns:
        - Response: The HTTP response generated by the middleware or route handler.

        """
        method = request.method
        route = self.get_route(request)
        if not route:
            labels = {"method": method, "route": request.url.path, "instance": DEFAULT_INSTANCE_NAME}
            _UNMATCHED_ROUTE.add(1, labels)
            return await call_next(request)

        labels = {"method": method, "route": route, "instance": DEFAULT_INSTANCE_NAME}

        await _increment_active_count(method, route, DEFAULT_INSTANCE_NAME, 1)
        start_ns = time.perf_counter_ns()
        try:
            _REQUESTS.add(1, labels)
            response = await call_next(request)
            response_labels = labels.copy()
            response_labels["status_code"] = response.status_code
            response_labels["exception_type"] = "N/A"
            _RESPONSES.add(1, response_labels)
            return response
        except Exception as exc:
            response_labels = labels.copy()
            response_labels["status_code"] = 500
            response_labels["exception_type"] = str(type(exc))
            _RESPONSES.add(1, response_labels)
            raise exc
        finally:
            end_ns = time.perf_counter_ns()
            await _increment_active_count(method, route, DEFAULT_INSTANCE_NAME, -1)
            _REQUEST_PROCESSING_TIME.record(math.floor((end_ns - start_ns) / 1000000), labels)

    def get_route(self, request):
        """
        Retrieve the route path of the current HTTP request.

        Parameters:
        - request (Request): The incoming HTTP request.

        Returns:
        - str or None: The path of the matched route, or None if no matching route is found.
        """
        for route in request.app.routes:
            match, _ = route.matches(request.scope)
            if match == routing.Match.FULL:
                return route.path

        return None


def metrics():
    """
    Retrieve runtime metrics.

    Returned metrics will be in the Prometheus format.
    """
    registry = get_prometheus_registry()
    return fastapi.Response(content=prometheus.generate_latest(registry), media_type=prometheus.CONTENT_TYPE_LATEST)
