{{- if .Values.apps.controller.enabled -}}
{{- $svc := mergeOverwrite (deepCopy $.Values.defaults) (deepCopy $.Values.global) (deepCopy $.Values.apps.controller) -}}
{{- $jobTemplateSpecOverrides := $svc.serviceConfig.k8s.jobTemplateSpecOverrides -}}
{{- $ctx := (dict "svcName" "controller" "svc" $svc "root" $) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-job-template-spec-overrides"
  labels:
    {{- include "nv-svc-farm.app.labels" $ctx | nindent 4 }}
data:
  job_template_spec_overrides.json: |-
        {{ toPrettyJson $jobTemplateSpecOverrides | nindent 8 }}
{{- end }}
