{{- $dag := mergeOverwrite (deepCopy $.Values.defaults) (deepCopy $.Values.global) (deepCopy $.Values.apps.dag) -}}
{{- $ctx := (dict "svcName" "dag" "svc" $dag "root" $) -}}

{{- $mysql := .Values.external.mysql -}}
{{- if and $dag.enabled $dag.secret.create (not $mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "nv-svc-farm.app.fullname" $ctx) $dag.secret.name }}
type: Opaque
data:
  mysql-password: "{{ $mysql.auth.password | b64enc }}"
{{- end }}
