{{- $mergedJobsSvc := mergeOverwrite (deepCopy .Values.defaults) (deepCopy .Values.global) (deepCopy (index $.Values.apps "jobs")) -}}
{{- $ctx := dict "svcName" "jobs" "mergedSvc" $mergedJobsSvc "root" $ "Chart" .Chart "Release" .Release -}}
{{- if and $mergedJobsSvc.enabled  $mergedJobsSvc.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "nv-svc-farm.app.fullname" $ctx }}"
type: Opaque
data:
  api_key: "{{ (include "jobs.store.apiKey" $ctx ) | b64enc }}"
{{- if and $.Values.external.redis.auth.enabled $.Values.external.redis.auth.password }}
  {{ $.Values.external.redis.auth.existingSecretPasswordKey }}: "{{ $.Values.external.redis.auth.password | b64enc }}"
{{- end }}
{{- end }}

