{{- $tasks := mergeOverwrite (deepCopy $.Values.defaults) (deepCopy $.Values.global) (deepCopy $.Values.apps.tasks) -}}
{{- $ctx := (dict "svcName" "tasks" "svc" $tasks "root" $) -}}

{{- $mysql := .Values.external.mysql -}}
{{- if and $tasks.enabled $tasks.secret.create (not $mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "nv-svc-farm.app.fullname" $ctx) $tasks.secret.name }}
type: Opaque
data:
  mysql-password: "{{ $mysql.auth.password | b64enc }}"
{{- end }}
