// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { globalStyle } from "@vanilla-extract/css";

globalStyle(
    "nve-accordion-header:not(:defined), nve-accordion-content:not(:defined), nve-accordion:not(:defined), nve-accordion-group:not(:defined), nve-alert-banner:not(:defined), nve-alert-group:not(:defined), nve-alert:not(:defined), nve-badge:not(:defined), nve-breadcrumb:not(:defined), nve-button-group:not(:defined), nve-button:not(:defined), nve-card:not(:defined), nve-card-header:not(:defined), nve-card-content:not(:defined), nve-card-footer:not(:defined), nve-checkbox-group:not(:defined), nve-checkbox:not(:defined), nve-color:not(:defined), nve-combobox:not(:defined), nve-date:not(:defined), nve-datetime:not(:defined), nve-dialog-footer:not(:defined), nve-dialog-header:not(:defined), nve-dialog:not(:defined), nve-divider:not(:defined), nve-dot:not(:defined), nve-drawer-content:not(:defined), nve-drawer-footer:not(:defined), nve-drawer-header:not(:defined), nve-drawer:not(:defined), nve-dropdown-footer:not(:defined), nve-dropdown-header:not(:defined), nve-dropdown:not(:defined), nve-file:not(:defined), nve-control-group:not(:defined), nve-control-message:not(:defined), nve-control:not(:defined), nve-grid-cell:not(:defined), nve-grid-column:not(:defined), nve-grid-footer:not(:defined), nve-grid:not(:defined), nve-grid-header:not(:defined), nve-grid-placeholder:not(:defined), nve-grid-row:not(:defined), nve-icon-button:not(:defined), nve-icon:not(:defined), nve-input-group:not(:defined), nve-input:not(:defined), nve-json-viewer:not(:defined), nve-logo:not(:defined), nve-menu-item:not(:defined), nve-menu:not(:defined), nve-month:not(:defined), nve-notification-group:not(:defined), nve-notification:not(:defined), nve-page-loader:not(:defined), nve-pagination:not(:defined), nve-panel-header:not(:defined), nve-panel-content:not(:defined), nve-panel-footer:not(:defined), nve-panel:not(:defined), nve-password:not(:defined), nve-progress-bar:not(:defined), nve-progress-ring:not(:defined), nve-progressive-filter-chip:not(:defined), nve-radio-group:not(:defined), nve-radio:not(:defined), nve-range:not(:defined), nve-search:not(:defined), nve-select:not(:defined), nve-sort-button:not(:defined), nve-steps-item:not(:defined), nve-steps:not(:defined), nve-switch:not(:defined), nve-tabs-item:not(:defined), nve-tabs:not(:defined), nve-tag:not(:defined), nve-textarea:not(:defined), nve-time:not(:defined), nve-toast:not(:defined), nve-toggletip-footer:not(:defined), nve-toggletip-header:not(:defined), nve-toggletip:not(:defined), nve-toolbar:not(:defined), nve-tooltip:not(:defined), nve-week:not(:defined)",
    {
        opacity: 0,
    }
);
