// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// This file is auto-generated from theme.mts

import { createTheme } from "@vanilla-extract/css";

// Theme selectors for vanilla-extract
export const isLightModeSelector = "html[nve-theme=light] &";
export const isDarkModeSelector = "html[nve-theme=dark] &";

// Breakpoint conditions for sprinkles
export const breakpointConditions = {
    initial: {},
    xs: {
        "@media": "screen and (min-width: 304px)",
    },
    sm: {
        "@media": "screen and (min-width: 768px)",
    },
    md: {
        "@media": "screen and (min-width: 1280px)",
    },
    lg: {
        "@media": "screen and (min-width: 1768px)",
    },
    xl: {
        "@media": "screen and (min-width: 2160px)",
    },
};

export const [themeClass, theme] = createTheme({
    breakpoint: {
        initial: "",
        xs: "304px",
        sm: "768px",
        md: "1280px",
        lg: "1768px",
        xl: "2160px",
    },
    scale: {
        text: "var(--nve-ref-scale-text)",
        size: "var(--nve-ref-scale-size)",
        space: "var(--nve-ref-scale-space)",
        borderRadius: "var(--nve-ref-scale-border-radius)",
        borderWidth: "var(--nve-ref-scale-border-width)",
        lineHeight: "var(--nve-ref-scale-line-height)",
    },
    size: {
        size50: "var(--nve-ref-size-50)",
        size100: "var(--nve-ref-size-100)",
        size150: "var(--nve-ref-size-150)",
        size200: "var(--nve-ref-size-200)",
        size250: "var(--nve-ref-size-250)",
        size300: "var(--nve-ref-size-300)",
        size400: "var(--nve-ref-size-400)",
        size500: "var(--nve-ref-size-500)",
        size600: "var(--nve-ref-size-600)",
        size700: "var(--nve-ref-size-700)",
        size800: "var(--nve-ref-size-800)",
        size900: "var(--nve-ref-size-900)",
        size1000: "var(--nve-ref-size-1000)",
    },
    space: {
        xxxs: "var(--nve-ref-space-xxxs)",
        xxs: "var(--nve-ref-space-xxs)",
        xs: "var(--nve-ref-space-xs)",
        sm: "var(--nve-ref-space-sm)",
        md: "var(--nve-ref-space-md)",
        lg: "var(--nve-ref-space-lg)",
        xl: "var(--nve-ref-space-xl)",
        xxl: "var(--nve-ref-space-xxl)",
        xxxl: "var(--nve-ref-space-xxxl)",
    },
    color: {
        white: "var(--nve-ref-color-white)",
        black: "var(--nve-ref-color-black)",
        alphaWhite100: "var(--nve-ref-color-alpha-white-100)",
        alphaWhite200: "var(--nve-ref-color-alpha-white-200)",
        alphaWhite300: "var(--nve-ref-color-alpha-white-300)",
        alphaWhite400: "var(--nve-ref-color-alpha-white-400)",
        alphaWhite500: "var(--nve-ref-color-alpha-white-500)",
        alphaWhite600: "var(--nve-ref-color-alpha-white-600)",
        alphaWhite700: "var(--nve-ref-color-alpha-white-700)",
        alphaWhite800: "var(--nve-ref-color-alpha-white-800)",
        alphaWhite900: "var(--nve-ref-color-alpha-white-900)",
        alphaWhite1000: "var(--nve-ref-color-alpha-white-1000)",
        alphaWhite1100: "var(--nve-ref-color-alpha-white-1100)",
        alphaWhite1200: "var(--nve-ref-color-alpha-white-1200)",
        alphaBlack100: "var(--nve-ref-color-alpha-black-100)",
        alphaBlack200: "var(--nve-ref-color-alpha-black-200)",
        alphaBlack300: "var(--nve-ref-color-alpha-black-300)",
        alphaBlack400: "var(--nve-ref-color-alpha-black-400)",
        alphaBlack500: "var(--nve-ref-color-alpha-black-500)",
        alphaBlack600: "var(--nve-ref-color-alpha-black-600)",
        alphaBlack700: "var(--nve-ref-color-alpha-black-700)",
        alphaBlack800: "var(--nve-ref-color-alpha-black-800)",
        alphaBlack900: "var(--nve-ref-color-alpha-black-900)",
        alphaBlack1000: "var(--nve-ref-color-alpha-black-1000)",
        alphaBlack1100: "var(--nve-ref-color-alpha-black-1100)",
        alphaBlack1200: "var(--nve-ref-color-alpha-black-1200)",
        brandGreen100: "var(--nve-ref-color-brand-green-100)",
        brandGreen200: "var(--nve-ref-color-brand-green-200)",
        brandGreen300: "var(--nve-ref-color-brand-green-300)",
        brandGreen400: "var(--nve-ref-color-brand-green-400)",
        brandGreen500: "var(--nve-ref-color-brand-green-500)",
        brandGreen600: "var(--nve-ref-color-brand-green-600)",
        brandGreen700: "var(--nve-ref-color-brand-green-700)",
        brandGreen800: "var(--nve-ref-color-brand-green-800)",
        brandGreen900: "var(--nve-ref-color-brand-green-900)",
        brandGreen1000: "var(--nve-ref-color-brand-green-1000)",
        brandGreen1100: "var(--nve-ref-color-brand-green-1100)",
        brandGreen1200: "var(--nve-ref-color-brand-green-1200)",
        yellowNova100: "var(--nve-ref-color-yellow-nova-100)",
        yellowNova200: "var(--nve-ref-color-yellow-nova-200)",
        yellowNova300: "var(--nve-ref-color-yellow-nova-300)",
        yellowNova400: "var(--nve-ref-color-yellow-nova-400)",
        yellowNova500: "var(--nve-ref-color-yellow-nova-500)",
        yellowNova600: "var(--nve-ref-color-yellow-nova-600)",
        yellowNova700: "var(--nve-ref-color-yellow-nova-700)",
        yellowNova800: "var(--nve-ref-color-yellow-nova-800)",
        yellowNova900: "var(--nve-ref-color-yellow-nova-900)",
        yellowNova1000: "var(--nve-ref-color-yellow-nova-1000)",
        yellowNova1100: "var(--nve-ref-color-yellow-nova-1100)",
        yellowNova1200: "var(--nve-ref-color-yellow-nova-1200)",
        limePear100: "var(--nve-ref-color-lime-pear-100)",
        limePear200: "var(--nve-ref-color-lime-pear-200)",
        limePear300: "var(--nve-ref-color-lime-pear-300)",
        limePear400: "var(--nve-ref-color-lime-pear-400)",
        limePear500: "var(--nve-ref-color-lime-pear-500)",
        limePear600: "var(--nve-ref-color-lime-pear-600)",
        limePear700: "var(--nve-ref-color-lime-pear-700)",
        limePear800: "var(--nve-ref-color-lime-pear-800)",
        limePear900: "var(--nve-ref-color-lime-pear-900)",
        limePear1000: "var(--nve-ref-color-lime-pear-1000)",
        limePear1100: "var(--nve-ref-color-lime-pear-1100)",
        limePear1200: "var(--nve-ref-color-lime-pear-1200)",
        greenJade100: "var(--nve-ref-color-green-jade-100)",
        greenJade200: "var(--nve-ref-color-green-jade-200)",
        greenJade300: "var(--nve-ref-color-green-jade-300)",
        greenJade400: "var(--nve-ref-color-green-jade-400)",
        greenJade500: "var(--nve-ref-color-green-jade-500)",
        greenJade600: "var(--nve-ref-color-green-jade-600)",
        greenJade700: "var(--nve-ref-color-green-jade-700)",
        greenJade800: "var(--nve-ref-color-green-jade-800)",
        greenJade900: "var(--nve-ref-color-green-jade-900)",
        greenJade1000: "var(--nve-ref-color-green-jade-1000)",
        greenJade1100: "var(--nve-ref-color-green-jade-1100)",
        greenJade1200: "var(--nve-ref-color-green-jade-1200)",
        pinkRose100: "var(--nve-ref-color-pink-rose-100)",
        pinkRose200: "var(--nve-ref-color-pink-rose-200)",
        pinkRose300: "var(--nve-ref-color-pink-rose-300)",
        pinkRose400: "var(--nve-ref-color-pink-rose-400)",
        pinkRose500: "var(--nve-ref-color-pink-rose-500)",
        pinkRose600: "var(--nve-ref-color-pink-rose-600)",
        pinkRose700: "var(--nve-ref-color-pink-rose-700)",
        pinkRose800: "var(--nve-ref-color-pink-rose-800)",
        pinkRose900: "var(--nve-ref-color-pink-rose-900)",
        pinkRose1000: "var(--nve-ref-color-pink-rose-1000)",
        pinkRose1100: "var(--nve-ref-color-pink-rose-1100)",
        pinkRose1200: "var(--nve-ref-color-pink-rose-1200)",
        purpleLavender100: "var(--nve-ref-color-purple-lavender-100)",
        purpleLavender200: "var(--nve-ref-color-purple-lavender-200)",
        purpleLavender300: "var(--nve-ref-color-purple-lavender-300)",
        purpleLavender400: "var(--nve-ref-color-purple-lavender-400)",
        purpleLavender500: "var(--nve-ref-color-purple-lavender-500)",
        purpleLavender600: "var(--nve-ref-color-purple-lavender-600)",
        purpleLavender700: "var(--nve-ref-color-purple-lavender-700)",
        purpleLavender800: "var(--nve-ref-color-purple-lavender-800)",
        purpleLavender900: "var(--nve-ref-color-purple-lavender-900)",
        purpleLavender1000: "var(--nve-ref-color-purple-lavender-1000)",
        purpleLavender1100: "var(--nve-ref-color-purple-lavender-1100)",
        purpleLavender1200: "var(--nve-ref-color-purple-lavender-1200)",
        purpleViolet100: "var(--nve-ref-color-purple-violet-100)",
        purpleViolet200: "var(--nve-ref-color-purple-violet-200)",
        purpleViolet300: "var(--nve-ref-color-purple-violet-300)",
        purpleViolet400: "var(--nve-ref-color-purple-violet-400)",
        purpleViolet500: "var(--nve-ref-color-purple-violet-500)",
        purpleViolet600: "var(--nve-ref-color-purple-violet-600)",
        purpleViolet700: "var(--nve-ref-color-purple-violet-700)",
        purpleViolet800: "var(--nve-ref-color-purple-violet-800)",
        purpleViolet900: "var(--nve-ref-color-purple-violet-900)",
        purpleViolet1000: "var(--nve-ref-color-purple-violet-1000)",
        purpleViolet1100: "var(--nve-ref-color-purple-violet-1100)",
        purpleViolet1200: "var(--nve-ref-color-purple-violet-1200)",
        purplePlum100: "var(--nve-ref-color-purple-plum-100)",
        purplePlum200: "var(--nve-ref-color-purple-plum-200)",
        purplePlum300: "var(--nve-ref-color-purple-plum-300)",
        purplePlum400: "var(--nve-ref-color-purple-plum-400)",
        purplePlum500: "var(--nve-ref-color-purple-plum-500)",
        purplePlum600: "var(--nve-ref-color-purple-plum-600)",
        purplePlum700: "var(--nve-ref-color-purple-plum-700)",
        purplePlum800: "var(--nve-ref-color-purple-plum-800)",
        purplePlum900: "var(--nve-ref-color-purple-plum-900)",
        purplePlum1000: "var(--nve-ref-color-purple-plum-1000)",
        purplePlum1100: "var(--nve-ref-color-purple-plum-1100)",
        purplePlum1200: "var(--nve-ref-color-purple-plum-1200)",
        pinkMagenta100: "var(--nve-ref-color-pink-magenta-100)",
        pinkMagenta200: "var(--nve-ref-color-pink-magenta-200)",
        pinkMagenta300: "var(--nve-ref-color-pink-magenta-300)",
        pinkMagenta400: "var(--nve-ref-color-pink-magenta-400)",
        pinkMagenta500: "var(--nve-ref-color-pink-magenta-500)",
        pinkMagenta600: "var(--nve-ref-color-pink-magenta-600)",
        pinkMagenta700: "var(--nve-ref-color-pink-magenta-700)",
        pinkMagenta800: "var(--nve-ref-color-pink-magenta-800)",
        pinkMagenta900: "var(--nve-ref-color-pink-magenta-900)",
        pinkMagenta1000: "var(--nve-ref-color-pink-magenta-1000)",
        pinkMagenta1100: "var(--nve-ref-color-pink-magenta-1100)",
        pinkMagenta1200: "var(--nve-ref-color-pink-magenta-1200)",
        redTomato100: "var(--nve-ref-color-red-tomato-100)",
        redTomato200: "var(--nve-ref-color-red-tomato-200)",
        redTomato300: "var(--nve-ref-color-red-tomato-300)",
        redTomato400: "var(--nve-ref-color-red-tomato-400)",
        redTomato500: "var(--nve-ref-color-red-tomato-500)",
        redTomato600: "var(--nve-ref-color-red-tomato-600)",
        redTomato700: "var(--nve-ref-color-red-tomato-700)",
        redTomato800: "var(--nve-ref-color-red-tomato-800)",
        redTomato900: "var(--nve-ref-color-red-tomato-900)",
        redTomato1000: "var(--nve-ref-color-red-tomato-1000)",
        redTomato1100: "var(--nve-ref-color-red-tomato-1100)",
        redTomato1200: "var(--nve-ref-color-red-tomato-1200)",
        orangePumpkin100: "var(--nve-ref-color-orange-pumpkin-100)",
        orangePumpkin200: "var(--nve-ref-color-orange-pumpkin-200)",
        orangePumpkin300: "var(--nve-ref-color-orange-pumpkin-300)",
        orangePumpkin400: "var(--nve-ref-color-orange-pumpkin-400)",
        orangePumpkin500: "var(--nve-ref-color-orange-pumpkin-500)",
        orangePumpkin600: "var(--nve-ref-color-orange-pumpkin-600)",
        orangePumpkin700: "var(--nve-ref-color-orange-pumpkin-700)",
        orangePumpkin800: "var(--nve-ref-color-orange-pumpkin-800)",
        orangePumpkin900: "var(--nve-ref-color-orange-pumpkin-900)",
        orangePumpkin1000: "var(--nve-ref-color-orange-pumpkin-1000)",
        orangePumpkin1100: "var(--nve-ref-color-orange-pumpkin-1100)",
        orangePumpkin1200: "var(--nve-ref-color-orange-pumpkin-1200)",
        yellowAmber100: "var(--nve-ref-color-yellow-amber-100)",
        yellowAmber200: "var(--nve-ref-color-yellow-amber-200)",
        yellowAmber300: "var(--nve-ref-color-yellow-amber-300)",
        yellowAmber400: "var(--nve-ref-color-yellow-amber-400)",
        yellowAmber500: "var(--nve-ref-color-yellow-amber-500)",
        yellowAmber600: "var(--nve-ref-color-yellow-amber-600)",
        yellowAmber700: "var(--nve-ref-color-yellow-amber-700)",
        yellowAmber800: "var(--nve-ref-color-yellow-amber-800)",
        yellowAmber900: "var(--nve-ref-color-yellow-amber-900)",
        yellowAmber1000: "var(--nve-ref-color-yellow-amber-1000)",
        yellowAmber1100: "var(--nve-ref-color-yellow-amber-1100)",
        yellowAmber1200: "var(--nve-ref-color-yellow-amber-1200)",
        greenGrass100: "var(--nve-ref-color-green-grass-100)",
        greenGrass200: "var(--nve-ref-color-green-grass-200)",
        greenGrass300: "var(--nve-ref-color-green-grass-300)",
        greenGrass400: "var(--nve-ref-color-green-grass-400)",
        greenGrass500: "var(--nve-ref-color-green-grass-500)",
        greenGrass600: "var(--nve-ref-color-green-grass-600)",
        greenGrass700: "var(--nve-ref-color-green-grass-700)",
        greenGrass800: "var(--nve-ref-color-green-grass-800)",
        greenGrass900: "var(--nve-ref-color-green-grass-900)",
        greenGrass1000: "var(--nve-ref-color-green-grass-1000)",
        greenGrass1100: "var(--nve-ref-color-green-grass-1100)",
        greenGrass1200: "var(--nve-ref-color-green-grass-1200)",
        tealSeafoam100: "var(--nve-ref-color-teal-seafoam-100)",
        tealSeafoam200: "var(--nve-ref-color-teal-seafoam-200)",
        tealSeafoam300: "var(--nve-ref-color-teal-seafoam-300)",
        tealSeafoam400: "var(--nve-ref-color-teal-seafoam-400)",
        tealSeafoam500: "var(--nve-ref-color-teal-seafoam-500)",
        tealSeafoam600: "var(--nve-ref-color-teal-seafoam-600)",
        tealSeafoam700: "var(--nve-ref-color-teal-seafoam-700)",
        tealSeafoam800: "var(--nve-ref-color-teal-seafoam-800)",
        tealSeafoam900: "var(--nve-ref-color-teal-seafoam-900)",
        tealSeafoam1000: "var(--nve-ref-color-teal-seafoam-1000)",
        tealSeafoam1100: "var(--nve-ref-color-teal-seafoam-1100)",
        tealSeafoam1200: "var(--nve-ref-color-teal-seafoam-1200)",
        greenMint100: "var(--nve-ref-color-green-mint-100)",
        greenMint200: "var(--nve-ref-color-green-mint-200)",
        greenMint300: "var(--nve-ref-color-green-mint-300)",
        greenMint400: "var(--nve-ref-color-green-mint-400)",
        greenMint500: "var(--nve-ref-color-green-mint-500)",
        greenMint600: "var(--nve-ref-color-green-mint-600)",
        greenMint700: "var(--nve-ref-color-green-mint-700)",
        greenMint800: "var(--nve-ref-color-green-mint-800)",
        greenMint900: "var(--nve-ref-color-green-mint-900)",
        greenMint1000: "var(--nve-ref-color-green-mint-1000)",
        greenMint1100: "var(--nve-ref-color-green-mint-1100)",
        greenMint1200: "var(--nve-ref-color-green-mint-1200)",
        tealCyan100: "var(--nve-ref-color-teal-cyan-100)",
        tealCyan200: "var(--nve-ref-color-teal-cyan-200)",
        tealCyan300: "var(--nve-ref-color-teal-cyan-300)",
        tealCyan400: "var(--nve-ref-color-teal-cyan-400)",
        tealCyan500: "var(--nve-ref-color-teal-cyan-500)",
        tealCyan600: "var(--nve-ref-color-teal-cyan-600)",
        tealCyan700: "var(--nve-ref-color-teal-cyan-700)",
        tealCyan800: "var(--nve-ref-color-teal-cyan-800)",
        tealCyan900: "var(--nve-ref-color-teal-cyan-900)",
        tealCyan1000: "var(--nve-ref-color-teal-cyan-1000)",
        tealCyan1100: "var(--nve-ref-color-teal-cyan-1100)",
        tealCyan1200: "var(--nve-ref-color-teal-cyan-1200)",
        blueSky100: "var(--nve-ref-color-blue-sky-100)",
        blueSky200: "var(--nve-ref-color-blue-sky-200)",
        blueSky300: "var(--nve-ref-color-blue-sky-300)",
        blueSky400: "var(--nve-ref-color-blue-sky-400)",
        blueSky500: "var(--nve-ref-color-blue-sky-500)",
        blueSky600: "var(--nve-ref-color-blue-sky-600)",
        blueSky700: "var(--nve-ref-color-blue-sky-700)",
        blueSky800: "var(--nve-ref-color-blue-sky-800)",
        blueSky900: "var(--nve-ref-color-blue-sky-900)",
        blueSky1000: "var(--nve-ref-color-blue-sky-1000)",
        blueSky1100: "var(--nve-ref-color-blue-sky-1100)",
        blueSky1200: "var(--nve-ref-color-blue-sky-1200)",
        blueCobalt100: "var(--nve-ref-color-blue-cobalt-100)",
        blueCobalt200: "var(--nve-ref-color-blue-cobalt-200)",
        blueCobalt300: "var(--nve-ref-color-blue-cobalt-300)",
        blueCobalt400: "var(--nve-ref-color-blue-cobalt-400)",
        blueCobalt500: "var(--nve-ref-color-blue-cobalt-500)",
        blueCobalt600: "var(--nve-ref-color-blue-cobalt-600)",
        blueCobalt700: "var(--nve-ref-color-blue-cobalt-700)",
        blueCobalt800: "var(--nve-ref-color-blue-cobalt-800)",
        blueCobalt900: "var(--nve-ref-color-blue-cobalt-900)",
        blueCobalt1000: "var(--nve-ref-color-blue-cobalt-1000)",
        blueCobalt1100: "var(--nve-ref-color-blue-cobalt-1100)",
        blueCobalt1200: "var(--nve-ref-color-blue-cobalt-1200)",
        blueIndigo100: "var(--nve-ref-color-blue-indigo-100)",
        blueIndigo200: "var(--nve-ref-color-blue-indigo-200)",
        blueIndigo300: "var(--nve-ref-color-blue-indigo-300)",
        blueIndigo400: "var(--nve-ref-color-blue-indigo-400)",
        blueIndigo500: "var(--nve-ref-color-blue-indigo-500)",
        blueIndigo600: "var(--nve-ref-color-blue-indigo-600)",
        blueIndigo700: "var(--nve-ref-color-blue-indigo-700)",
        blueIndigo800: "var(--nve-ref-color-blue-indigo-800)",
        blueIndigo900: "var(--nve-ref-color-blue-indigo-900)",
        blueIndigo1000: "var(--nve-ref-color-blue-indigo-1000)",
        blueIndigo1100: "var(--nve-ref-color-blue-indigo-1100)",
        blueIndigo1200: "var(--nve-ref-color-blue-indigo-1200)",
        neutral100: "var(--nve-ref-color-neutral-100)",
        neutral200: "var(--nve-ref-color-neutral-200)",
        neutral300: "var(--nve-ref-color-neutral-300)",
        neutral400: "var(--nve-ref-color-neutral-400)",
        neutral500: "var(--nve-ref-color-neutral-500)",
        neutral600: "var(--nve-ref-color-neutral-600)",
        neutral700: "var(--nve-ref-color-neutral-700)",
        neutral800: "var(--nve-ref-color-neutral-800)",
        neutral900: "var(--nve-ref-color-neutral-900)",
        neutral1000: "var(--nve-ref-color-neutral-1000)",
        neutral1100: "var(--nve-ref-color-neutral-1100)",
        neutral1200: "var(--nve-ref-color-neutral-1200)",
        grayDenim100: "var(--nve-ref-color-gray-denim-100)",
        grayDenim200: "var(--nve-ref-color-gray-denim-200)",
        grayDenim300: "var(--nve-ref-color-gray-denim-300)",
        grayDenim400: "var(--nve-ref-color-gray-denim-400)",
        grayDenim500: "var(--nve-ref-color-gray-denim-500)",
        grayDenim600: "var(--nve-ref-color-gray-denim-600)",
        grayDenim700: "var(--nve-ref-color-gray-denim-700)",
        grayDenim800: "var(--nve-ref-color-gray-denim-800)",
        grayDenim900: "var(--nve-ref-color-gray-denim-900)",
        grayDenim1000: "var(--nve-ref-color-gray-denim-1000)",
        grayDenim1100: "var(--nve-ref-color-gray-denim-1100)",
        grayDenim1200: "var(--nve-ref-color-gray-denim-1200)",
        graySlate100: "var(--nve-ref-color-gray-slate-100)",
        graySlate200: "var(--nve-ref-color-gray-slate-200)",
        graySlate300: "var(--nve-ref-color-gray-slate-300)",
        graySlate400: "var(--nve-ref-color-gray-slate-400)",
        graySlate500: "var(--nve-ref-color-gray-slate-500)",
        graySlate600: "var(--nve-ref-color-gray-slate-600)",
        graySlate700: "var(--nve-ref-color-gray-slate-700)",
        graySlate800: "var(--nve-ref-color-gray-slate-800)",
        graySlate900: "var(--nve-ref-color-gray-slate-900)",
        graySlate1000: "var(--nve-ref-color-gray-slate-1000)",
        graySlate1100: "var(--nve-ref-color-gray-slate-1100)",
        graySlate1200: "var(--nve-ref-color-gray-slate-1200)",
        redCardinal100: "var(--nve-ref-color-red-cardinal-100)",
        redCardinal200: "var(--nve-ref-color-red-cardinal-200)",
        redCardinal300: "var(--nve-ref-color-red-cardinal-300)",
        redCardinal400: "var(--nve-ref-color-red-cardinal-400)",
        redCardinal500: "var(--nve-ref-color-red-cardinal-500)",
        redCardinal600: "var(--nve-ref-color-red-cardinal-600)",
        redCardinal700: "var(--nve-ref-color-red-cardinal-700)",
        redCardinal800: "var(--nve-ref-color-red-cardinal-800)",
        redCardinal900: "var(--nve-ref-color-red-cardinal-900)",
        redCardinal1000: "var(--nve-ref-color-red-cardinal-1000)",
        redCardinal1100: "var(--nve-ref-color-red-cardinal-1100)",
        redCardinal1200: "var(--nve-ref-color-red-cardinal-1200)",
        scheme: "var(--nve-sys-color-scheme)",
    },
    fontFamily: {
        default: "var(--nve-ref-font-family)",
        inter: "var(--nve-ref-font-family-inter)",
        robotoMono: "var(--nve-ref-font-family-roboto-mono)",
    },
    fontWeight: {
        light: "var(--nve-ref-font-weight-light)",
        regular: "var(--nve-ref-font-weight-regular)",
        medium: "var(--nve-ref-font-weight-medium)",
        semibold: "var(--nve-ref-font-weight-semibold)",
        bold: "var(--nve-ref-font-weight-bold)",
        extraBold: "var(--nve-ref-font-weight-extra-bold)",
    },
    fontSize: {
        fontSize50: "var(--nve-ref-font-size-50)",
        fontSize100: "var(--nve-ref-font-size-100)",
        fontSize200: "var(--nve-ref-font-size-200)",
        fontSize300: "var(--nve-ref-font-size-300)",
        fontSize400: "var(--nve-ref-font-size-400)",
        fontSize500: "var(--nve-ref-font-size-500)",
        fontSize600: "var(--nve-ref-font-size-600)",
        fontSize700: "var(--nve-ref-font-size-700)",
        fontSize800: "var(--nve-ref-font-size-800)",
        fontSize900: "var(--nve-ref-font-size-900)",
        fontSize1000: "var(--nve-ref-font-size-1000)",
        fontSize1100: "var(--nve-ref-font-size-1100)",
        fontSize1200: "var(--nve-ref-font-size-1200)",
    },
    fontLineHeight: {
        fontLineHeight300: "var(--nve-ref-font-line-height-300)",
        fontLineHeight400: "var(--nve-ref-font-line-height-400)",
        fontLineHeight500: "var(--nve-ref-font-line-height-500)",
        fontLineHeight600: "var(--nve-ref-font-line-height-600)",
        fontLineHeight700: "var(--nve-ref-font-line-height-700)",
        fontLineHeight800: "var(--nve-ref-font-line-height-800)",
        fontLineHeight900: "var(--nve-ref-font-line-height-900)",
        fontLineHeight1000: "var(--nve-ref-font-line-height-1000)",
        tight: "var(--nve-ref-font-line-height-tight)",
        snug: "var(--nve-ref-font-line-height-snug)",
        moderate: "var(--nve-ref-font-line-height-moderate)",
        relaxed: "var(--nve-ref-font-line-height-relaxed)",
        loose: "var(--nve-ref-font-line-height-loose)",
    },
    borderRadius: {
        none: "var(--nve-ref-border-radius-none)",
        xs: "var(--nve-ref-border-radius-xs)",
        sm: "var(--nve-ref-border-radius-sm)",
        md: "var(--nve-ref-border-radius-md)",
        lg: "var(--nve-ref-border-radius-lg)",
        xl: "var(--nve-ref-border-radius-xl)",
        xxl: "var(--nve-ref-border-radius-xxl)",
        full: "var(--nve-ref-border-radius-full)",
    },
    borderWidth: {
        sm: "var(--nve-ref-border-width-sm)",
        md: "var(--nve-ref-border-width-md)",
        lg: "var(--nve-ref-border-width-lg)",
        xl: "var(--nve-ref-border-width-xl)",
    },
    borderColor: {
        default: "var(--nve-ref-border-color)",
        emphasis: "var(--nve-ref-border-color-emphasis)",
        muted: "var(--nve-ref-border-color-muted)",
        inverse: "var(--nve-ref-border-color-inverse)",
    },
    opacity: {
        opacity0: "var(--nve-ref-opacity-0)",
        opacity150: "var(--nve-ref-opacity-150)",
        opacity200: "var(--nve-ref-opacity-200)",
        opacity300: "var(--nve-ref-opacity-300)",
        opacity400: "var(--nve-ref-opacity-400)",
        opacity500: "var(--nve-ref-opacity-500)",
        opacity600: "var(--nve-ref-opacity-600)",
        opacity700: "var(--nve-ref-opacity-700)",
        opacity800: "var(--nve-ref-opacity-800)",
        opacity900: "var(--nve-ref-opacity-900)",
    },
    shadow: {
        shadow100: "var(--nve-ref-shadow-100)",
        shadow200: "var(--nve-ref-shadow-200)",
        shadow300: "var(--nve-ref-shadow-300)",
        shadow400: "var(--nve-ref-shadow-400)",
        shadow500: "var(--nve-ref-shadow-500)",
        shadow600: "var(--nve-ref-shadow-600)",
        shadow700: "var(--nve-ref-shadow-700)",
        shadow800: "var(--nve-ref-shadow-800)",
    },
    outline: {
        default: "var(--nve-ref-outline)",
        webkit: "var(--nve-ref-outline-webkit)",
    },
    animation: {
        duration100: "var(--nve-ref-animation-duration-100)",
        duration200: "var(--nve-ref-animation-duration-200)",
        duration300: "var(--nve-ref-animation-duration-300)",
        duration400: "var(--nve-ref-animation-duration-400)",
        easing100: "var(--nve-ref-animation-easing-100)",
    },
    text: {
        color: "var(--nve-sys-text-color)",
        mutedColor: "var(--nve-sys-text-muted-color)",
        emphasisColor: "var(--nve-sys-text-emphasis-color)",
        placeholderColor: "var(--nve-sys-text-placeholder-color)",
        whiteColor: "var(--nve-sys-text-white-color)",
        blackColor: "var(--nve-sys-text-black-color)",
        linkColor: "var(--nve-sys-text-link-color)",
        linkHoverColor: "var(--nve-sys-text-link-hover-color)",
        linkVisitedColor: "var(--nve-sys-text-link-visited-color)",
        linkDisabledColor: "var(--nve-sys-text-link-disabled-color)",
        linkEmphasisColor: "var(--nve-sys-text-link-emphasis-color)",
    },
    accent: {
        primaryBackground: "var(--nve-sys-accent-primary-background)",
        secondaryBackground: "var(--nve-sys-accent-secondary-background)",
        tertiaryBackground: "var(--nve-sys-accent-tertiary-background)",
    },
    contrast: {
        emphasisColor: "var(--nve-sys-contrast-emphasis-color)",
        emphasisRatio: "var(--nve-sys-contrast-emphasis-ratio)",
        muteColor: "var(--nve-sys-contrast-mute-color)",
        muteRatio: "var(--nve-sys-contrast-mute-ratio)",
    },
    interaction: {
        color: "var(--nve-sys-interaction-color)",
        background: "var(--nve-sys-interaction-background)",
        background100: "var(--nve-sys-interaction-background-100)",
        background200: "var(--nve-sys-interaction-background-200)",
        background300: "var(--nve-sys-interaction-background-300)",
        fieldColor: "var(--nve-sys-interaction-field-color)",
        fieldBackground: "var(--nve-sys-interaction-field-background)",
        fieldBackground100: "var(--nve-sys-interaction-field-background-100)",
        fieldBackground200: "var(--nve-sys-interaction-field-background-200)",
        fieldBackground300: "var(--nve-sys-interaction-field-background-300)",
        emphasisColor: "var(--nve-sys-interaction-emphasis-color)",
        emphasisBackground: "var(--nve-sys-interaction-emphasis-background)",
        destructiveColor: "var(--nve-sys-interaction-destructive-color)",
        destructiveBackground:
            "var(--nve-sys-interaction-destructive-background)",
        highlightedColor: "var(--nve-sys-interaction-highlighted-color)",
        highlightedBackground:
            "var(--nve-sys-interaction-highlighted-background)",
        highlightedMutedBackground:
            "var(--nve-sys-interaction-highlighted-muted-background)",
        disabledColor: "var(--nve-sys-interaction-disabled-color)",
        disabledBackground: "var(--nve-sys-interaction-disabled-background)",
        selectedColor: "var(--nve-sys-interaction-selected-color)",
        selectedBackground: "var(--nve-sys-interaction-selected-background)",
        stateBase: "var(--nve-sys-interaction-state-base)",
        stateMix: "var(--nve-sys-interaction-state-mix)",
        stateRatio: "var(--nve-sys-interaction-state-ratio)",
        stateRatioHover: "var(--nve-sys-interaction-state-ratio-hover)",
        stateRatioDisabled: "var(--nve-sys-interaction-state-ratio-disabled)",
        stateRatioActive: "var(--nve-sys-interaction-state-ratio-active)",
        stateRatioSelected: "var(--nve-sys-interaction-state-ratio-selected)",
        emphasizeColor: "var(--nve-sys-interaction-emphasize-color)",
        emphasizeBackground: "var(--nve-sys-interaction-emphasize-background)",
        secondaryColor: "var(--nve-sys-interaction-secondary-color)",
        secondaryBackground: "var(--nve-sys-interaction-secondary-background)",
    },
    layer: {
        canvasBackground: "var(--nve-sys-layer-canvas-background)",
        canvasColor: "var(--nve-sys-layer-canvas-color)",
        canvasAccentBackground: "var(--nve-sys-layer-canvas-accent-background)",
        shellBackground: "var(--nve-sys-layer-shell-background)",
        shellColor: "var(--nve-sys-layer-shell-color)",
        shellAccentBackground: "var(--nve-sys-layer-shell-accent-background)",
        containerBackground: "var(--nve-sys-layer-container-background)",
        containerColor: "var(--nve-sys-layer-container-color)",
        containerAccentBackground:
            "var(--nve-sys-layer-container-accent-background)",
        overlayBackground: "var(--nve-sys-layer-overlay-background)",
        overlayColor: "var(--nve-sys-layer-overlay-color)",
        overlayAccentBackground:
            "var(--nve-sys-layer-overlay-accent-background)",
        backdropBackground: "var(--nve-sys-layer-backdrop-background)",
        popoverBackground: "var(--nve-sys-layer-popover-background)",
        popoverColor: "var(--nve-sys-layer-popover-color)",
        popoverAccentBackground:
            "var(--nve-sys-layer-popover-accent-background)",
        popoverOffset: "var(--nve-sys-layer-popover-offset)",
        popoverArrowOffset: "var(--nve-sys-layer-popover-arrow-offset)",
        popoverArrowPadding: "var(--nve-sys-layer-popover-arrow-padding)",
    },
    status: {
        color: "var(--nve-sys-status-color)",
        scheduledColor: "var(--nve-sys-status-scheduled-color)",
        queuedColor: "var(--nve-sys-status-queued-color)",
        pendingColor: "var(--nve-sys-status-pending-color)",
        startingColor: "var(--nve-sys-status-starting-color)",
        runningColor: "var(--nve-sys-status-running-color)",
        restartingColor: "var(--nve-sys-status-restarting-color)",
        stoppingColor: "var(--nve-sys-status-stopping-color)",
        finishedColor: "var(--nve-sys-status-finished-color)",
        failedColor: "var(--nve-sys-status-failed-color)",
        unknownColor: "var(--nve-sys-status-unknown-color)",
        ignoredColor: "var(--nve-sys-status-ignored-color)",
    },
    support: {
        color: "var(--nve-sys-support-color)",
        mutedColor: "var(--nve-sys-support-muted-color)",
        emphasisColor: "var(--nve-sys-support-emphasis-color)",
        accentColor: "var(--nve-sys-support-accent-color)",
        accentMutedColor: "var(--nve-sys-support-accent-muted-color)",
        accentEmphasisColor: "var(--nve-sys-support-accent-emphasis-color)",
        successColor: "var(--nve-sys-support-success-color)",
        successMutedColor: "var(--nve-sys-support-success-muted-color)",
        successEmphasisColor: "var(--nve-sys-support-success-emphasis-color)",
        dangerColor: "var(--nve-sys-support-danger-color)",
        dangerMutedColor: "var(--nve-sys-support-danger-muted-color)",
        dangerEmphasisColor: "var(--nve-sys-support-danger-emphasis-color)",
        warningColor: "var(--nve-sys-support-warning-color)",
        warningMutedColor: "var(--nve-sys-support-warning-muted-color)",
        warningEmphasisColor: "var(--nve-sys-support-warning-emphasis-color)",
    },
    visualization: {
        categoricalViolet: "var(--nve-sys-visualization-categorical-violet)",
        categoricalLavender:
            "var(--nve-sys-visualization-categorical-lavender)",
        categoricalRose: "var(--nve-sys-visualization-categorical-rose)",
        categoricalRed: "var(--nve-sys-visualization-categorical-red)",
        categoricalPumpkin: "var(--nve-sys-visualization-categorical-pumpkin)",
        categoricalAmber: "var(--nve-sys-visualization-categorical-amber)",
        categoricalNova: "var(--nve-sys-visualization-categorical-nova)",
        categoricalPear: "var(--nve-sys-visualization-categorical-pear)",
        categoricalGrass: "var(--nve-sys-visualization-categorical-grass)",
        categoricalSeafoam: "var(--nve-sys-visualization-categorical-seafoam)",
        categoricalCyan: "var(--nve-sys-visualization-categorical-cyan)",
        categoricalSlate: "var(--nve-sys-visualization-categorical-slate)",
        sequentialDivergingVirdis100:
            "var(--nve-sys-visualization-sequential-diverging-virdis-100)",
        sequentialDivergingVirdis200:
            "var(--nve-sys-visualization-sequential-diverging-virdis-200)",
        sequentialDivergingVirdis300:
            "var(--nve-sys-visualization-sequential-diverging-virdis-300)",
        sequentialDivergingVirdis400:
            "var(--nve-sys-visualization-sequential-diverging-virdis-400)",
        sequentialDivergingVirdis500:
            "var(--nve-sys-visualization-sequential-diverging-virdis-500)",
        sequentialDivergingVirdis600:
            "var(--nve-sys-visualization-sequential-diverging-virdis-600)",
        sequentialDivergingVirdis700:
            "var(--nve-sys-visualization-sequential-diverging-virdis-700)",
        sequentialDivergingVirdis800:
            "var(--nve-sys-visualization-sequential-diverging-virdis-800)",
        sequentialDivergingVirdis900:
            "var(--nve-sys-visualization-sequential-diverging-virdis-900)",
        sequentialDivergingVirdis1000:
            "var(--nve-sys-visualization-sequential-diverging-virdis-1000)",
        sequentialDivergingVirdis1100:
            "var(--nve-sys-visualization-sequential-diverging-virdis-1100)",
        sequentialDivergingVirdis1200:
            "var(--nve-sys-visualization-sequential-diverging-virdis-1200)",
        sequentialDivergingVirdis1300:
            "var(--nve-sys-visualization-sequential-diverging-virdis-1300)",
        sequentialDivergingVirdis1400:
            "var(--nve-sys-visualization-sequential-diverging-virdis-1400)",
        sequentialDivergingVirdis1500:
            "var(--nve-sys-visualization-sequential-diverging-virdis-1500)",
        sequentialDivergingRedGreen100:
            "var(--nve-sys-visualization-sequential-diverging-red-green-100)",
        sequentialDivergingRedGreen200:
            "var(--nve-sys-visualization-sequential-diverging-red-green-200)",
        sequentialDivergingRedGreen300:
            "var(--nve-sys-visualization-sequential-diverging-red-green-300)",
        sequentialDivergingRedGreen400:
            "var(--nve-sys-visualization-sequential-diverging-red-green-400)",
        sequentialDivergingRedGreen500:
            "var(--nve-sys-visualization-sequential-diverging-red-green-500)",
        sequentialDivergingRedGreen600:
            "var(--nve-sys-visualization-sequential-diverging-red-green-600)",
        sequentialDivergingRedGreen700:
            "var(--nve-sys-visualization-sequential-diverging-red-green-700)",
        sequentialDivergingRedGreen800:
            "var(--nve-sys-visualization-sequential-diverging-red-green-800)",
        sequentialDivergingRedGreen900:
            "var(--nve-sys-visualization-sequential-diverging-red-green-900)",
        trendNegativeColor: "var(--nve-sys-visualization-trend-negative-color)",
        trendNegativeEmphasisColor:
            "var(--nve-sys-visualization-trend-negative-emphasis-color)",
        trendPositiveColor: "var(--nve-sys-visualization-trend-positive-color)",
        trendPositiveEmphasisColor:
            "var(--nve-sys-visualization-trend-positive-emphasis-color)",
    },
});
